repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        files: \.py$
        always_run: true
        stages: [commit]  

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest tests/
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]  