paths:
  root: '/c/Users/busen/Blue-Yonder/bike_sharing_challenge'

model:
  model_type: 'RandomForestRegressor' # ['LinearRegressor', 'RandomForestRegressor', 'XGBoostRegressor', 'LGBMRegressor']
  model_params:
    random_state: 42
    n_estimators: 100
    learning_rate: 0.1
    criterion: 'squared_error' # ['squared_error', 'absolute_error', 'friedman_mse', 'poisson']
    max_depth: None 
    hidden_layer_sizes: (100, 100)
    activation: 'relu'
    max_iter: 500

training:
  test_size: 0.2

evaluation:
  metric: "MAE" # ["MAE", "RMSE"]

logging:
  level: "INFO"
  file: "logs/training.log"