paths:
  root: '/c/Users/busen/Blue-Yonder/bike_sharing_challenge'

model:
  model_type: 'random_forest' # ['linear_regression', 'gradient_boosting', 'decision_tree', 'random_forest', 'mlp_regressor', 'xgboost', 'lightgbm']
  model_params:
    random_state: 42
    n_estimators: 100
    learning_rate: 0.1
    criterion: 'squared_error' # ['squared_error', 'absolute_error', 'friedman_mse', 'poisson']
    max_depth: None 
    hidden_layer_sizes: (100, 100)
    activation: 'relu'
    max_iter: 500

training:
  test_size: 0.2

evaluation:
  metric: "mae" # ["mae", "mse", "rmse"]

logging:
  level: "INFO"
  file: "logs/training.log"

data:
  categorical_features:
    one_hot_encoding: [] # ['weathersit', 'season']
  numerical_features:
    standard_scaler: [] # ['temp', 'atemp', 'hum', 'windspeed']
    sine_cosine_transformation: [] # ['hr', 'mnth', 'weekday']
  pca_transformation:
    n_components: 0
  target_column: 'cnt'
